### ISSUE TITLE
Rounding of large numbers by mistake

### ISSUE THREAD

**Issue by ghost** [abap2xlsx/abap2xlsx#917] opened 2021-12-14 06:12 UTC
Hi ;)
when calling method load_file of class zcl_excel_reader_2007 to read large numbers with two decimal places, the number in the excel sheet gets rounded by mistake.
Example:
![image](https://user-images.githubusercontent.com/96047728/145942999-592208e1-0523-4c9d-b749-bdec4b8ea6c7.png)

[large_number_example.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/7709079/large_number_example.xlsx)
[zdemo_excel43_modified.txt](https://github.com/abap2xlsx/abap2xlsx/files/7709110/zdemo_excel43_modified.txt)

**Comment by sandraros** [comment] 2021-12-14 14:46
Thank you. I can reproduce.

First analysis is that Excel displays with 2 digits after decimal point, but stores internally 2468214.3199999998, because Excel stores numbers internally as binary floating-point numbers (type F in ABAP). So abap2xlsx is right when reading the number in a character field, it truncates a string of characters, not a number, and gives result `2468214.319`.

In your demo program if you change the field of the 4th column from type C length 13 to type P with big length and 2 digits after decimal point, and skip the heading line, it will work perfectly:
```abap
*         d(13) TYPE c.
         d     TYPE p LENGTH 15 DECIMALS 2.
```
and
```abap
*        lo_worksheet->get_table( IMPORTING et_table = lt_tab ).
        lo_worksheet->get_table( EXPORTING iv_skipped_rows = 1 IMPORTING et_table = lt_tab ).
```

**Comment by sandraros** [comment] 2021-12-24 08:56
If it answers your question, could you close the issue please, or do you need further assistance? Thank you.

**Comment by sandraros** [comment] 2022-01-08 11:16
No answer. Closing. You may reopen it if you want. Thank you.

**Closed as completed by sandraros** 2022-01-08 11:16 UTC
Labels: question
