### ISSUE TITLE
Only 255 sheets allowed in worksheet

### ISSUE THREAD

**Issue by StefanSchmoecker** [abap2xlsx/abap2xlsx#530] opened 2018-03-21 10:27 UTC
Currently ABAP2XLSX dumps when creating a document with more than 255 worksheets.  Reason is the definition of DTEL ZEXCEL_ACTIVE_WORKSHEET which is defined as 1-byte integer.   
Excel specification does not limit the number of sheet (any more?). 
Suggestion - change dataelement to 2-byte or 4 byte integer  ( Unfortunatly my reference system is no up to date atm  since I had no time to update to ABAPGit yet )
Testprogram with an enlarged dataelement ( 2-bytes ) allowed me to create larger documents.

**Comment by ivanfemia** [comment] 2018-03-21 13:44
There was a similar issue, that I can't find right know. I think this was already been fixed.

**Comment by bilencekic** [comment] 2018-04-24 08:10
lol this issue was a fight reason with one of my colleagues. we had an excel file with macro content which is done by me and he was reading the content and adding data to the sheets. We were making stress test with multiple sheets and at some point it start giving corrupted error. He was blaming me and i was saying my macro is fine. I said excel class might have issue after certain amount of sheets. That day i keep silent or i would be fired or jailed :D. Good to know it is due to this limitation. In my current project, this class is the core functionality of overall application :) god bless ivanfemia and all contributors.

**Comment by AtomKrieg** [comment] 2018-08-19 21:55
Not fixed yet. Look at file zexcel_active_worksheet.dtel.xml:

`<DOMNAME>INT1</DOMNAME>`

dump will be in ZCL_EXCEL->GET_WORKSHEET_BY_INDEX (uncatched CX_SY_CONVERSION_OVERFLOW):

```
   DATA: lv_index TYPE zexcel_active_worksheet.`

   lv_index = iv_index.
```
code example for dump:
```
    data(excel) = new zcl_excel( ).
    try.
        data(ws) = excel->get_worksheet_by_index( 999 ).
      catch cx_root into data(lx).
        message lx type 'I' display like 'E'.
    endtry.
```

**Comment by sandraros** [comment] 2021-09-24 20:44
Pay attention to #557 which says that it was possible to write more than 1000 sheets at that time -> after the fix of current issue, make sure that the case in #557 works.

**Comment by sandraros** [comment] 2021-11-11 21:01
I confirm that the bug still exists, impossible to create more than 255 sheets. Program to reproduce the bug:
```
REPORT.
DATA: gc_save_file_name TYPE string VALUE 'issue_530.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.
START-OF-SELECTION.
  DATA(lo_excel) = NEW zcl_excel( ).
  DO 300 TIMES.
    DATA(lo_worksheet) = lo_excel->add_new_worksheet( |Sheet{ sy-index + 1 }| ).
  ENDDO.
  lo_worksheet = lo_excel->get_worksheet_by_index( 290 ).
  ASSERT lo_worksheet->get_title( ) = 'Sheet290'.
  lcl_output=>output( lo_excel ).
```
A quick fix of data element `zexcel_active_worksheet` from `INT1` to `INT4` seems to solve the bug.

**Closed as completed** 2021-12-29 04:42 UTC
Labels: bug
