### ISSUE TITLE
WRITER_2007 Produces Wrong XML Tag for Conditional Formatting

### ISSUE THREAD

**Issue by ghost** [abap2xlsx/abap2xlsx#422] opened 2016-02-09 15:32 UTC
Hello community,

if I load with the demo program ZDEMO_EXCEL37 an XLSX file with conditional formatting and save it to frontend the XML tag of the conditional formatting is wrong. I expected conditionalFormatting sqref="D38:D43" but the WRITER_2007 generates conditionalFormatting sqref="A1 D38:D43". The READER_2007 dumps if it reads this kind of conditional formatting, the A1 with the following space is wrong.

Thanks in advance.

Cheers
Stefan

Test XLSX file: [Mappe1.xlsx](https://github.com/sapmentors/abap2xlsx/files/123244/Mappe1.xlsx)
Result XLSX file: [37- Read template and output.xlsx](https://github.com/sapmentors/abap2xlsx/files/123247/37-.Read.template.and.output.xlsx)

**Comment by sandraros** [comment] 2021-12-01 22:03
Unfortunately I can't reproduce the issue with the latest version of abap2xlsx. As it was a long time ago, maybe the issue has been fixed. 

Text XLSX file: same as above "Mappe1.xlsx"
Result XLSX file: [37- Read template and output.xlsx](https://github.com/sapmentors/abap2xlsx/files/7637409/37-.Read.template.and.output.xlsx)

Could you confirm whether it's fine for you or not?
Thank you.

**Comment by sandraros** [comment] 2021-12-26 17:16
No answer. Closing.

**Closed as completed by sandraros** 2021-12-26 17:16 UTC
Labels: invalid
