### ISSUE TITLE
Wrongly changed worksheet dimension

### ISSUE THREAD

**Issue by chemik3** [abap2xlsx/abap2xlsx#722] opened 2021-01-25 13:45 UTC
When I open file input.xlsx with zcl_excel_reader_2007 and immediately write with zcl_excel_writer_2007. New file had changed format, from row 17 is changed font size from 11 to 12. In source file sheet1.xml are tags which generated file don't have:

https://imgur.com/3KyEdyp

For test you can use test program: https://drive.google.com/file/d/18Z8mCteUvR9v15JB49ALtkKXczmgPLg0/view?usp=sharing 
import xlsx file: https://drive.google.com/file/d/1EhjF5NhfUlRMu3Sao8_A9jnBaqE7v3r-/view?usp=sharing

**Comment by sandraros** [comment] 2021-01-27 09:52
Problem reproduced. For information, I can see that the UsedRange of the sheet has changed. Original UsedRange (press Ctrl+End) is AY784 (`<dimension ref="A1:AY784"/>`), while the generated file UsedRange is AY16 (`<dimension ref="A2:AY16"/>`). In the original one, I see that AY784 has font size 11, but the next rows have font size 12.

**Comment by sandraros** [comment] 2021-02-13 17:27
Analysis...
So, the original XLSX file is like this one, with a lot of formatting, different row heights, different styles with different font sizes, but the cells are empty:
![image](https://user-images.githubusercontent.com/34005250/107852695-8254e300-6e12-11eb-89bc-90f4ee02bedb.png)

In the XML file of the original sheet, we can see that the last row with cells inside is the row 16, but there are extra rows up to row 784 with style, custom format and height:
![image](https://user-images.githubusercontent.com/34005250/107852659-59345280-6e12-11eb-9ab4-934000855c0e.png)

When the custom program calls the method READ_FILE, after that the SHEET_CONTENT attribute of the worksheet object has last cell at position AY16:
![image](https://user-images.githubusercontent.com/34005250/107852742-bcbe8000-6e12-11eb-92d4-a1eb3b286313.png)

and the ROWS attribute of the worksheet object has only 3 rows (1):
![image](https://user-images.githubusercontent.com/34005250/107852774-e4ade380-6e12-11eb-8c91-00b8d19f5a9c.png)
(1) because the XML attribute "customHeight" is "1" (ECMA-376 says "1 if the row height has been manually set."):
![image](https://user-images.githubusercontent.com/34005250/107853111-67836e00-6e14-11eb-97fa-080975655e3b.png)
(all other row heights in that XML are calculated automatically by Excel based on their cell contents, because of e.g. font size assigned to rows)
and the method LOAD_WORKSHEET of ZCL_EXCEL_READER_2007 creates the row object only if "customHeight" is "1":
![image](https://user-images.githubusercontent.com/34005250/107855628-dae0ac00-6e23-11eb-87e5-c446993a0972.png)

**The code above seems a little bit wrong to me, as the height should be considered even if `customHeight` is false (absent or '0'), because as I said previously the height may be calculated by autofit (according to font size, etc.) when creating manually the XLSX file. I suggest that the row object is always created when the `<row>` element is present in the XLSX file. The "custom height" attribute should be added to the class ZCL_EXCEL_ROW, and the parameter "custom height" should be added to the method `set_row_height` (with default value "true").**

When the custom program calls the method WRITE_FILE of ZCL_EXCEL_WRITER_2007 > calls CREATE > calls CREATE_XL_SHEET of ZCL_EXCEL_WORKSHEET > calls GET_DIMENSION_RANGE > calls UPDATE_DIMENSION_RANGE which calculates the new worksheet dimension based on the attribute SHEET_CONTENT ⇒ `A2:AY16`.

**I suggest that the dimension also considers the attribute ROWS. The method CREATE_XL_SHEET_SHEET_DATA which writes the rows and cells must also be changed to take into account the new attribute "custom height".**

**Comment by sandraros** [comment] 2021-02-13 18:13
This issue has two distinct problems: the worksheet dimension and the lost default row style (font size for instance). It's too much complex to solve the two in one correction, so I have created #740 to correct the second issue.

**Closed as completed** 2021-07-03 17:07 UTC
Labels: bug
