### ISSUE TITLE
New bug in ZDEMO_EXCEL29

### ISSUE THREAD

**Issue by PENGFARLEY** [abap2xlsx/abap2xlsx#687] opened 2020-08-24 00:38 UTC
Dear Team,,

I found a new bug when I try to run the demo program: ZDEMO_EXCEL29 with a Macro-enabled Workbook.
 There is an ABAP Dump in line 64: lv_file = lo_excel_writer->write_file( lo_excel ).
 when I debug I found: the first row the table LO_WORKSHEET->SHEET_CONTENT, the cell_row value is 0.

**Comment by PENGFARLEY** [comment] 2020-08-24 00:45
you can take this test macro workbook to run the demo program: ZDEMO_EXCEL29, the you will get the ABAP Dump error.

Thanks.

**Comment by sandraros** [comment] 2021-02-12 08:20
The "test macro workbook" is missing, could you attach it please?

**Comment by PENGFARLEY** [comment] 2021-03-18 03:56
> is missing, could yo

Hi Sandraros,
I have attached the file, could you try again?
Thanks.
[test macro workbook.zip](https://github.com/sapmentors/abap2xlsx/files/6161188/test.macro.workbook.zip)

**Comment by sandraros** [comment] 2021-03-18 13:35
> I have attached the file, could you try again?

Thank you. I will analyze it this evening.

**Comment by sandraros** [comment] 2021-03-18 19:44
Analysis is over: in your Excel file, in `/xl/worksheets/sheet1.xml` there is an hyperlink which spans over several cells:
```
<hyperlinks>
  <hyperlink ref="C4" r:id="rId1" tooltip="NPR TRAINING DOCUMENT.doc" xr:uid="{00000000-0004-0000-0200-000000000000}"/>
  <hyperlink ref="C5:C8" r:id="rId2" tooltip="NPR TRAINING DOCUMENT.doc" display="DOC" xr:uid="{00000000-0004-0000-0200-000002000000}"/>
</hyperlinks>
```
The method LOAD_WORKSHEET_HYPERLINKS of ZCL_EXCEL_READER_2007 handles hyperlinks over one cell only, as you can see here https://github.com/sapmentors/abap2xlsx/blob/master/src/zcl_excel_reader_2007.clas.abap#L3456-L3471, the method `convert_columnrow2column_a_row` receives `I_COLUMNROW = 'C5:C8'` and returns `E_ROW = 0`:
```
      zcl_excel_common=>convert_columnrow2column_a_row( EXPORTING
                                                          i_columnrow = ls_hyperlink-ref
                                                        IMPORTING
                                                          e_row       = lv_row
                                                          e_column    = lv_column ).
      io_worksheet->get_cell( EXPORTING
                                ip_column     = lv_column
                                 ip_row       = lv_row
                               IMPORTING
                                 ep_value     = lv_value ).
      io_worksheet->set_cell( ip_column     = lv_column
                              ip_row        = lv_row
                              ip_value      = lv_value
                              ip_hyperlink  = lo_hyperlink ).
```
Solution to be proposed. Back soon...

**Comment by sandraros** [comment] 2021-03-20 17:02
NB: this problem is not related to XLSM file and ZDEMO_EXCEL29. It may happen even with a simple XLSX file that can be used with ZDEMO_EXCEL37 to reproduce the issue. Example of minimal XLSX file: 
[test fix 687.zip](https://github.com/sapmentors/abap2xlsx/files/6176005/test.fix.687.zip)

**Comment by sandraros** [comment] 2021-03-20 17:15
The fix above solves the ABAP dump, which was due to a same hyperlink assigned to a range of cells. Note that after the fix, I could see other issues concerning the Excel file provided, like the hyperlink is not underlined and color is not blue, and the VBA button is not rendered (please create separate issues if you want them to be resolved).

**Closed as completed** 2021-05-21 19:15 UTC
Labels: bug
