### ISSUE TITLE
Writer XML encoding

### ISSUE THREAD

**Issue by ivanfemia** [abap2xlsx/abap2xlsx#307] opened 2014-03-12 19:57 UTC
Move the encoding schema "UTF-8" as an attribute of the WRITER class (by default UTF-8, but it can be modified in UTF-16).

See issue #298 for details.

**Comment by StefanSchmoecker** [comment] 2015-08-12 08:50
Cleanup of open issues:
This topic is older than one year:  Unless someone comments that this topic should be kept as an open issue I'll close this in about two weeks time.

**Comment by gregorwolf** [comment] 2015-09-20 11:03
Please check my sample code at http://scn.sap.com/thread/3801086 showing problems with UTF-8 using ixml.

**Comment by sandraros** [comment] 2021-12-26 16:40
I understand that the issue is about rendering all Unicode characters, which has been solved by #743 and #757, so closing.

**Closed as completed by sandraros** 2021-12-26 16:40 UTC
Labels: enhancement
