### ISSUE TITLE
Reader doesn't detect any worksheet

### ISSUE THREAD

**Issue by ToniRivas** [abap2xlsx/abap2xlsx#447] opened 2016-07-29 10:23 UTC
Hello,
I'm new in using abap2xlsx and I have a problem I can not understand.
I have an Excel xlsx that comes from an external product and when charged with LOAD_FILE method does nothing.

```
  CALL METHOD reader-> load_file
    EXPORTING
      i_filename = ip_filename
      = sy-batch i_from_applserver
    RECEIVING
      r_excel = excel.
```

 It could be a problem in versions of Excel because if I open it and I record is generated as Excel 2007 and works properly.
When you open both versions with zip I've seen some differences, which does not work the labels start with X: ... .. (x: workbook, x: sheets) instead which I rerecorded not have the x: ... (worbook, sheets ).
The point where we generated the fault is in the LOAD_WORKBOOK method at the point where includes the sheet name, here LO_NODE initial value is not collected anything.
- ------------------------------------------------- ------------------- *
-   Â§3.1    Names and order of of worksheets
- ------------------------------------------------- ------------------- *
  lo_node? = lo_workbook-> find_from_name ( 'sheet').
  
  I am doing something wrong?
  The issue is that it is an automatic process and can not be opened and re-record Excel.
  Also attached Excel code before and after if it helps and the bad file

Thank you in advance for your help.
Toni Rivas

[SAP_A_0028_malo__01_07292016100000.xlsx](https://github.com/sapmentors/abap2xlsx/files/390327/SAP_A_0028_malo__01_07292016100000.xlsx)

![image](https://user-images.githubusercontent.com/34005250/142776081-5f4fc4ec-c330-4335-9ce9-914029031dbd.png)

Bad
```xml
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
<x:workbook xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
            mc:Ignorable="x15"
            xmlns:x15="http://schemas.microsoft.com/office/spreadsheetml/2010/11/main"
            xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
            xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
            xmlns:x15ac="http://schemas.microsoft.com/office/spreadsheetml/2010/11/ac">
    <x:fileVersion rupBuild="14420" lowestEdited="6" lastEdited="6" appName="xl" />
    <x:workbookPr defaultThemeVersion="153222" />
    <mc:AlternateContent xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006">
        <mc:Choice Requires="x15">
            <x15ac:absPath="http://schemas.microsoft.com/office/spreadsheetml/2010/11/ac" url="C:\Users\101950~l\AppData\Local\Temp\InformationServer\" />
        </mc:Choice>
    </mc:AlternateContent>
    <x:bookViews>
        <x:workbookView windowHeight="11595" windowWidth="19200" yWindow="0" xWindow="0" />
    </x:bookViews>
    <x:sheets>
        <x:sheet r:id="rId1" sheetId="1" name="NUM_1" />
        <x:sheet r:id="rId2" sheetId="2" name="BW" />
        <x:sheet r:id="rId3" sheetId="3" name="NUM_3" />
    </x:sheets>
    <x:calcPr forceFullCalc="1" fullCalcOnLoad="1" calcId="152511" />
    <x:extLst>
        <x:ext xmlns:x15="http://schemas.microsoft.com/office/spreadsheetml/2010/11/main" uri="{140A7094-0E35-4892-8432-C4D2E57EDEB5}">
            <x15:workbookPr chartTrackingRefBase="1" />
        </x:ext>
    </x:extLst>
</x:workbook>
```

Good
```xml
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
<workbook xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
    <fileVersion rupBuild="4507" lowestEdited="6" lastEdited="4" appName="xl" />
    <workbookPr />
    <bookViews>
        <workbookView windowHeight="11595" windowWidth="19200" yWindow="0" xWindow="0" />
    </bookViews>
    <sheets>
        <sheet r:id="rId1" sheetId="1" name="NUM_1" />
        <sheet r:id="rId2" sheetId="2" name="BW" />
        <sheet r:id="rId3" sheetId="3" name="NUM_3" />
    </sheets>
    <calcPr forceFullCalc="1" calcId="125725" />
    <x:extLst xmlns:x15="http://schemas.microsoft.com/office/spreadsheetml/2010/11/main" xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
        <x:ext uri="{140A7094-0E35-4892-8432-C4D2E57EDEB5}">
            <x15:workbookPr chartTrackingRefBase="1" />
        </x:ext>
    </x:extLst>
</workbook>
```

**Comment by sandraros** [comment] 2021-11-21 19:26
To reproduce, run the program `ZDEMO_EXCEL37` to display the attached Excel file. It shows an empty workbook, although there should be 3 tabs, some texts, etc.:
![image](https://user-images.githubusercontent.com/34005250/142776136-e399a6b4-01e2-4c50-ba55-563bf7a4f699.png)

**Comment by sandraros** [comment] 2021-11-21 20:44
This can be fixed by changing as shown below. But it means that many lines of code in abap2xlsx which use `find_from_name` are potentially wrong: instead of using a fixed namespace prefix (or none as in the current issue), we should replace all of them with `find_from_name_ns` with the full URI. The only place where it could be right are the writer classes, because the namespace prefixes are chosen by abap2xlsx.

Proposed fix:
- The culprit line in method `LOAD_WORKBOOK` of `ZCL_EXCEL_READER_2007`
 
https://github.com/abap2xlsx/abap2xlsx/blob/68707e1469e8a39982f0a672fb8788c3be15337f/src/zcl_excel_reader_2007.clas.abap#L1951
- must be replaced with
  ```abap
    lo_node ?= lo_workbook->find_from_name_ns( name = 'sheet' uri = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main' ).
  ```

**Closed as completed** 2022-01-15 16:05 UTC
Labels: bug
