### ISSUE TITLE
Use of Column Formula (zdemo_excel47) generates corrupted Excel

### ISSUE THREAD

**Issue by tk-am501** [abap2xlsx/abap2xlsx#1198] opened 2024-03-25 18:27 UTC
EDIT March 27th: this issue is about Column Formulas (`zdemo_excel47`) which generate corrupted Excel file.

Hello,

i have the same problem like in [Issue 723](https://github.com/abap2xlsx/abap2xlsx/issues/723). I have Office 365 and the formular don´t work.

I always get the error, when opening Excel.
![image](https://github.com/abap2xlsx/abap2xlsx/assets/138573610/3b1ac3be-774e-457f-9b85-a6890a51b767)

I also tried this: [SAP Community](https://community.sap.com/t5/application-development-blog-posts/abap2xlsx-experience-with/ba-p/13221069) but this doesn´t work either.

```
 LO_WORKSHEET = LO_EXCEL->GET_ACTIVE_WORKSHEET( ).
 LO_WORKSHEET->SET_TITLE( IP_TITLE = 'KUG-Planung' ).
 LO_WORKSHEET->FREEZE_PANES( IP_NUM_COLUMNS = 3 IP_NUM_ROWS = 1 ).

 LS_TABLE_SETTINGS-TABLE_STYLE       = ZCL_EXCEL_TABLE=>BUILTINSTYLE_MEDIUM2.
 LS_TABLE_SETTINGS-SHOW_ROW_STRIPES  = ABAP_TRUE.
 LS_TABLE_SETTINGS-NOFILTERS         = ABAP_TRUE.
*LS_TABLE_SETTINGS-TABLE_NAME        = 'KUG'.

  LT_FIELD_CATALOG = ZCL_EXCEL_COMMON=>GET_FIELDCATALOG( IP_TABLE = GT_KUG_30 ).
        LOOP AT LT_FIELD_CATALOG ASSIGNING FIELD-SYMBOL(<ls>).
          IF <LS>-FIELDNAME = 'KUG_DAYS'.
             <ls>-SCRTEXT_M = 'KUG'.
             <ls>-SCRTEXT_S = 'KUG'.
             <ls>-scrtext_l = 'Kurzarbeits-Tage'.
             <LS>-COLUMN_FORMULA = 'COUNTIF(P2:AS2;"K")'."'ZÄHLEWENN(P2:AS2;"K")'.
          ENDIF.
        ENDLOOP.

        LO_WORKSHEET->BIND_TABLE( IP_TABLE          = GT_KUG_30
*                                  IS_TABLE_SETTINGS = LS_TABLE_SETTINGS
                                  IT_FIELD_CATALOG  = LT_FIELD_CATALOG ).
```

If I put the fomurlar like normal it is working:
![image](https://github.com/abap2xlsx/abap2xlsx/assets/138573610/b1cb9fc7-ace5-43a1-8cc9-bae6f18da7b0)
Formular: =ZÄHLENWENN(P2:AS2;"K")

Testreport: ZDEMO_EXCEL47 also don´t work for me.
![image](https://github.com/abap2xlsx/abap2xlsx/assets/138573610/d4fc6b94-ad23-477a-ae10-0d8f1f2bc787)

**Comment by tk-am501** [comment] 2024-03-25 18:28
Sorry, I thought that the hyperlinks worked and the coding...

**Comment by tk-am501** [comment] 2024-03-25 18:30
If I put the fomurlar like normal it is working:
![image](https://github.com/abap2xlsx/abap2xlsx/assets/138573610/d4a11c63-2515-4a96-9d57-e3cdaff24d1d)
Formular: =ZÄHLENWENN(P2:AS2;"K")

**Comment by sandraros** [comment] 2024-03-26 10:18
Thank you for posting. It's not the same request as the feature request 723, in your case it's an issue, 723 was a feature request.

In your case, I think the issue is due to the use of the language-specific function names (like German `ZÄHLEWENN`), you should only use the **language-agnostic function names** (which are the same as the English names).

Either you use the [Microsoft Excel functions translator](https://support.microsoft.com/en-us/office/excel-functions-translator-f262d0c0-991c-485b-89b6-32cc8d326889?ui=en-us&rs=en-us&ad=us) (which I never tested), or you enter manually the formula `ZÄHLEWENN`, save and look directly into the .xlsx file (it's like a ZIP file).

**Comment by tk-am501** [comment] 2024-03-26 10:27
> Thank you for posting. It's not the same request as the feature request 723, in your case it's an issue, 723 was a feature request.
> 
> In your case, I think the issue is due to the use of the language-specific function names (like German `ZÄHLEWENN`), you should only use the **language-agnostic function names** (which are the same as the English names).
> 
> Either you use the [Microsoft Excel functions translator](https://support.microsoft.com/en-us/office/excel-functions-translator-f262d0c0-991c-485b-89b6-32cc8d326889?ui=en-us&rs=en-us&ad=us) (which I never tested), or you enter manually the formula `ZÄHLEWENN`, save and look directly into the .xlsx file (it's like a ZIP file).

Hey sandraros, 
the Problem is that I already tried the "language-agnostic function names". It doesn´t work either. The same as the testreport "ZDEMO_EXCEL47" which doesn´t work either, like the screenshot.

I think the Problem is, that the table can´t be recognized.

**Comment by tk-am501** [comment] 2024-03-26 10:30
And sorry the referencing Issue would be [Issue 905](https://github.com/abap2xlsx/abap2xlsx/issues/905).

**Comment by sandraros** [comment] 2024-03-26 10:38
The issue 905 is about the reader but your question is about creating a formula with `ZÄHLEWENN`. Could you fix your question and show how I can reproduce without effort please?

**Comment by tk-am501** [comment] 2024-03-26 11:32
Alright, so I try to build an Excel-File with the formula "ZÄHLEWENN" or in English "COUNTIF", but after downloading the file it shows the errror like above.

If I start the Report "ZDEMO_EXCEL47" I got the following problem for "Direct display":
![image](https://github.com/abap2xlsx/abap2xlsx/assets/138573610/69cf3c58-cdf6-4f25-a51d-628a406fd683)

If I download the file from the Report it also gives the same error. For example the file attached.
[47_ColumnFormulas.xlsx](https://github.com/abap2xlsx/abap2xlsx/files/14757631/47_ColumnFormulas.xlsx)

**Comment by sandraros** [comment] 2024-03-26 12:30
If I understand well, your only issue is in fact #905. If you have some ABAP expertise, would you mind developing a solution and proposing a Pull Request? For now, I would propose to close this current issue as it is a duplicate of #905.

**Comment by sandraros** [comment] 2024-03-27 09:22
Got it concerning `zdemo_excel47`. It's due to the login in German. It works in English.

In column E, the formula is `=[@Airfare]+100`
![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/9ee36eab-b098-4182-b7d4-288a44842e57)

If you connect in German, the column name is different:
![image](https://github.com/abap2xlsx/abap2xlsx/assets/34005250/142f8bba-897c-40cc-bee7-13ddb52b5840)

I will open an issue in the `demos` repository.

**Comment by sandraros** [comment] 2024-03-27 09:26
Now, back to your original issue, I don't think you really want to use the Excel feature of Column Formulas.

Your basic question is to use the formula `=COUNTIF(P2:AS2,"K")`. Pay attention to the fact that the formulas are internally stored with a comma, not a semi-colon.

I tested it, it works well.

**Comment by tk-am501** [comment] 2024-03-27 10:59
> Got it concerning `zdemo_excel47`. It's due to the login in German. It works in English.
> 
> In column E, the formula is `=[@Airfare]+100` ![image](https://private-user-images.githubusercontent.com/34005250/317187444-9ee36eab-b098-4182-b7d4-288a44842e57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzQ2MDksIm5iZiI6MTcxMTUzNDMwOSwicGF0aCI6Ii8zNDAwNTI1MC8zMTcxODc0NDQtOWVlMzZlYWItYjA5OC00MTgyLWI3ZDQtMjg4YTQ0ODQyZTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEwMTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MjQwMDhiNTI0NjBkZTY2ZTU1M2UxYWZhZWFmODMwOTQ0NDUzZTgwNTIzNzZkNzFkN2YzMjE3ZTA5ZGMxNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OVvPqdV6ADywfED0pzirurqIqs6XIXum0RCn_nCbkgA)
> 
> If you connect in German, the column name is different: ![image](https://private-user-images.githubusercontent.com/34005250/317197750-142f8bba-897c-40cc-bee7-13ddb52b5840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzQ2MDksIm5iZiI6MTcxMTUzNDMwOSwicGF0aCI6Ii8zNDAwNTI1MC8zMTcxOTc3NTAtMTQyZjhiYmEtODk3Yy00MGNjLWJlZTctMTNkZGI1MmI1ODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEwMTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNjJmNGI3NzBjMTg5NzFjYjMxODBjNDU5Y2VlZWJmYmViOGNiNmMzNmM1OGQxZGQxM2E4ZjJkYzQ4ZjY1MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uyWuFO7IkhhVIoP9MwgylBoqNS0aaQDoqDrLklPGcts)
> 
> I will open an issue in the `demos` repository.

Thank you very much.

**Comment by tk-am501** [comment] 2024-03-27 11:00
> Now, back to your original issue, I don't think you really want to use the Excel feature of Column Formulas.
> 
> Your basic question is to use the formula `=COUNTIF(P2:AS2,"K")`. Pay attention to the fact that the formulas are internally stored with a comma, not a semi-colon.
> 
> I tested it, it works well.

That is really the right solution. I didn´t tried it because I copied the Formular from the Excel Translator and it didn´t work.
Now it is working with the comma.
Thank you very much!

**Closed as completed** 2024-03-29 16:03 UTC
