### ISSUE TITLE
Column Header Label Long Description

### ISSUE THREAD

**Issue by Kunamifresquinho** [abap2xlsx/abap2xlsx#677] opened 2020-07-02 16:22 UTC
Hi, i am using ABAP2XLS to create an excel based on a table related to an SAP structure which has the fields defined as predefined type. I am using zcl_excel_common=>get_fieldcatalog method to get the field catalog for my sheet but i have to manually populate scrtext_l with the description of the DDIC so that i can have the fields descriptions in the excel file.
But, when the description is longer than 20chars, when i open the excel, it always shows me a popup saying that the file has a problem and it's going to recover data from excel.
I tried to use a workaround and fill the scrtext_s and scrtext_m fields, but then it uses always the value from scrtext_m field and the description gets truncated.
Does anyone knows a way to overcome this issue ?
Thanks for you help!

**Comment by sandraros** [comment] 2021-02-12 20:46
@Kunamifresquinho Could you provide a minimal code so that I can reproduce the error?
Thank you.
Note: this issue seems related to #726 but in that case the limit seems to be 40 characters and there's no error.

**Comment by sandraros** [comment] 2021-09-19 08:41
No answer. Closing.
There's no issue to output 40 characters by mentioning `iv_default_descr = 'L'` (means to output the long text) as in code below:
```
REPORT.
DATA: gc_save_file_name TYPE string VALUE 'wider_table_header_text.xlsx'.
INCLUDE zdemo_excel_outputopt_incl.

START-OF-SELECTION.
  SELECT carrid, carrname FROM scarr INTO TABLE @DATA(scarr) UP TO 1 ROWS.
  DATA(lo_excel) = NEW zcl_excel( ).
  DATA(lo_worksheet) = lo_excel->get_active_worksheet( ).
  DATA(lt_field_catalog) = zcl_excel_common=>get_fieldcatalog( ip_table = scarr ).
  LOOP AT lt_field_catalog ASSIGNING FIELD-SYMBOL(<ls_field_catalog>).
    <ls_field_catalog>-scrtext_l = |this is the widest possible column text{ sy-tabix }|.
  ENDLOOP.
  lo_worksheet->bind_table(
    EXPORTING
      ip_table            = scarr
      it_field_catalog    = lt_field_catalog
      is_table_settings   = VALUE zexcel_s_table_settings(
                              table_name       = 'RR'
                              top_left_column  = 'A'
                              top_left_row     = 1
                              show_row_stripes = abap_true )
      iv_default_descr    = 'L' ).
  lcl_output=>output( cl_excel = lo_excel ).
```

**Closed as completed by sandraros** 2021-09-19 08:41 UTC
Labels: question
